#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

#开始 代码检查拦截
TAG="pre-commit log----------------->"

#打印success日志函数
printS(){
   echo -e "\033[0;32m $* \033[0m"
}

#打印fail日志函数
printE(){
   echo -e "\033[0;31m $* \033[0m"
}

#获取脚本的根目录
SCRIPT_DIR=$(dirname "$0")
#echo "SCRIPT_DIR=$SCRIPT_DIR"
SCRIPT_ABS_PATH=`cd "$SCRIPT_DIR"; pwd`
#echo "SCRIPT_ABS_PATH=$SCRIPT_ABS_PATH"
#在app项目目录下执行 gradlew 命令执行 checkstyle task
$SCRIPT_ABS_PATH/../../gradlew  -P checkCommit="true" checkstyle
if [ $? -eq 0   ]; then
# checkstyle检查成功
    info=$TAG"checkstyle OK"
    printS $info
else
#checkstyle检查失败
    info=$TAG"checkstyle fail"
    printE $info
    exit 1
fi
#结束

# If you want to allow non-ASCII filenames set this variable to true.
allownonascii=$(git config --bool hooks.allownonascii)

# Redirect output to stderr.
exec 1>&2

# Cross platform projects tend to avoid non-ASCII filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ "$allownonascii" != "true" ] &&
	# Note that the use of brackets around a tr range is ok here, (it's
	# even required, for portability to Solaris 10's /usr/bin/tr), since
	# the square bracket bytes happen to fall in the designated range.
	test $(git diff --cached --name-only --diff-filter=A -z $against |
	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
	cat <<\EOF
Error: Attempt to add a non-ASCII file name.

This can cause problems if you want to work with people on other platforms.

To be portable it is advisable to rename the file.

If you know what you are doing you can disable this check using:

  git config hooks.allownonascii true
EOF
	exit 1
fi

# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached $against --
